### ISSUE TITLE
Write about page

### ISSUE THREAD

**Issue by DinhL3** [DinhL3/social-media-app#16]
Lend me thine ears, for I do send forth a humble request that thou mayst craft, with all due skill and grace, an "About" page for our social media app, wherein the essence of our vision might be conveyed.

TLDR: guy that is good at literature, please write the text of our About page.

**Comment by bynned** [comment]
@Narglar maybe could write some epic text, and then @JikruKakru could create the page and copy + paste the text made by @Narglar
